version: '3.8'

services:
  postgres:
    build: ./db
    container_name: my_postgres_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init-db.sh:/init-db.sh
      - ./db/schema.sql:/schema.sql
    networks:
      - app_network
    command: ["bash", "/init-db.sh"]

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8081:8080"
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
