version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: my_postgres_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - app_network
    command: ["bash", "/docker-entrypoint-initdb.d/init-db.sh"]

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
